name: CI
on:
  pull_request:
    branches:
      - dev
      - main
  push:
    branches:
      - main
jobs:
  build:
    uses: leelatechllc/.github/workflows/standard-docker-ci.yaml@main
    #with:
      #ecr-repository: honeycomb/register-api
      #ghp-url: "https://verbose-happiness-e7c18a87.pages.github.io"
    secrets:
      #nexus-username: ${{ secrets.NEXUS_USERNAME }}
      #nexus-password: ${{ secrets.NEXUS_PASSWORD }}
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_password: ${{ secrets.DOCKERHUB_TOKEN }}
