name: docker-ci

on:
  push:
    branches: main
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: "self-hosted"

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: ls
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}        
