name: docker-ci

on:
  push:
    branches: main
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: 
      labels: self-hosted
      group: Default

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello from Octo Organization
