name: docker-ci

on:
  push:
    branches: main
  pull_request:
    branches: dev

jobs:
  build:
    runs-on: "self-hosted"

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: ls

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Nexus Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY_URL}}
          username: ${{ secrets.DOCKER_USER}}
          password: ${{ secrets.DOCKER_PASS}}
      - name: Sets datetime tag
        run: echo "_DATE=$(date +%m%d%Y_%H%M)" >> $GITHUB_ENV
        
      - name: Shows datetime tag
        run: echo ${{ env._DATE }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          # platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKER_REGISTRY_URL}}/${{ github.event.repository.name }}:${{ env._DATE }}
            ${{ secrets.DOCKER_REGISTRY_URL}}/${{ github.event.repository.name }}:latest
          # ghcr.io/user/app:1.0.0                  

